export type {
  CameraAdapter,
  CameraDevice,
  CameraErrorEvent,
  CameraModule,
  CameraPermissions,
  CameraPosition,
  CameraReadyEvent,
  CameraViewMethods,
  CameraViewProps,
  CapturePhotoOptions,
  FlashMode,
  PermissionStatus,
  PhotoFile,
  Point,
  PreviewResizeMode,
  RecordingFinishedEvent,
  RecordingStartedEvent,
  Size,
  StartRecordingOptions,
  TargetCameraPosition,
  TorchMode,
  VideoFile,
} from './types.js'

export {
  LYNX_CAMERA_JS_VERSION,
  assertCameraInstalled,
  assertCameraInstalledAsync,
  createCameraAdapter,
  createNativeCameraAdapter,
  getCameraInstallStatus,
  getCameraInstallStatusAsync,
  getNativeCameraModule,
  type CameraInstallStatus,
  type CameraInstallStatusCode,
  type CreateCameraAdapterOptions,
} from './native.js'
