export type {
  CameraAdapter,
  CameraDevice,
  CameraErrorEvent,
  CameraModule,
  CameraFacing,
  CameraPingResult,
  CameraPermissions,
  CameraPosition,
  CameraReadyEvent,
  CameraSessionMethods,
  CameraViewMethods,
  CameraViewProps,
  CapturePhotoOptions,
  FlashMode,
  ImageOutputOptions,
  PermissionStatus,
  PickPhotoOptions,
  PhotoFile,
  Point,
  PreviewResizeMode,
  RecordingFinishedEvent,
  RecordingStartedEvent,
  Size,
  StartRecordingOptions,
  TargetCameraPosition,
  TorchMode,
  VideoFile,
} from './types.js'

export {
  CHIMERA_CAMERA_JS_VERSION,
  assertCameraInstalled,
  assertCameraInstalledAsync,
  createCameraAdapter,
  createNativeCameraAdapter,
  getCameraInstallStatus,
  getCameraInstallStatusAsync,
  getNativeCameraModule,
  type CameraInstallStatus,
  type CameraInstallStatusCode,
  type CreateCameraAdapterOptions,
} from './native.js'

export {
  CAMERA_VIEW_TAG,
  createCameraViewHandle,
  invokeCameraViewMethod,
  isCameraViewBridgeAvailable,
  type CameraViewHandle,
} from './view.js'
